=== Gajdascz/build-block/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Full Plugin Configuration",
  "type": "object",
  "required": ["core"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "URL to the JSON schema for this configuration file."
    },
    "core": { "$ref": "./templates/core.schema.json" },
    "npm": { "$ref": "./templates/npm.schema.json" },
    "php": { "$ref": "./templates/php.schema.json" },
    "wp": { "$ref": "./templates/wp-core.schema.json" },
    "block": { "$ref": "./templates/block/schema.json" }
  }
}

=== Gajdascz/build-block/examples/build-block.json
{
  "$schema": "../schemas/schema.json",
  "core": {
    "namespace": "example-namespace",
    "slug": "example-slug",
    "title": "Example Block",
    "description": "Example block description",
    "authorName": "Example Author",
    "authorEmail": "exampleAuthor@example.email.com",
    "authorUrl": "Example Author URL",
    "repository": "Example Repository",
    "funding": "Example Funding"
  },
  "block": {
    "__experimental": false,
    "ancestor": [],
    "allowedBlocks": [],
    "category": "widgets",
    "icon": "block-default",
    "keywords": ["example", "block"],
    "parent": [],
    "providesContext": {},
    "usesContext": [],
    "blockHooks": {},
    "example": {},
    "styles": [],
    "attributes": {
      "content": { "type": "string", "default": "" },
      "alignment": { "type": "string", "default": "left" },
      "backgroundColor": { "type": "string", "default": "#ffffff" },
      "showDetails": { "type": "boolean", "default": false }
    },
    "supports": {
      "interactivity": true,
      "align": true,
      "anchor": true,
      "className": true,
      "customClassName": true,
      "html": false,
      "inserter": true,
      "multiple": false,
      "reusable": false,
      "color": { "background": true, "text": true, "link": true },
      "spacing": { "blockGap": true, "margin": true, "padding": true }
    },

    "selectors": {},
    "variations": []
  },
  "npm": {
    "contributors": [{ "name": "Name is Required", "email": "", "url": "" }],
    "tags": [],
    "url": ""
  },
  "php": { "classScope": "ExampleNamespace", "methodScope": "exmplns" },
  "wp": {
    "contributors": [],
    "requiresPlugins": [],
    "tags": [],
    "updateUrl": ""
  }
}
